 services:
  - type: web
    name: esgi
    repo: https://github.com/render-examples/webdis.git # optional
#  # db 1
#   - name: prod
#     region: frankfurt
#     plan: pro
#     databaseName: prod_app
#     user: app_user
#     ipAllowList: # optional (defaults to allow all)
#       - source: 203.0.113.4/30
#         description: office
#       - source: 198.51.100.1
#         description: home
#     readReplicas: # optional (defaults to no replicas)
#       - name: prod-replica
databases:
  - name: esgidb
    databaseName: mydb # optional (Render may add a suffix)
    user: root # optional 
    host: DB_URL
    password: MYSQL_PASSWORD

