 services:
  - type: web
    name: esgi.render.nodejs2
    repo: https://github.com/Danosh95j/cloud4 # optional
    region: frankfurt
    buildCommand: npm run build
    startCommand: npm start

databases:
  - name: esgidb
    plan: free
    databaseName: mydb # optional (Render may add a suffix)
    user: root # optional 
    host: DB_URL
    password: MYSQL_PASSWORD
  - source: 127.0.0.1
    runtime: node

