 services:
  - type: web
    name: esgi.render.nodejs2
    repo: https://github.com/Danosh95j/cloud4 # optional
    region: frankfurt
    plan: free
    branch: main
    runtime: node
    buildCommand: yarn
    startCommand: npm start
    envVars:
      - key: DB_URL
        fromDatabase:
          name: esgi.render.nodejs2
          property: connectionString

 databases:
  - name: esgidb
    region: frankfurt
    plan: free
    user: root # optional 
    password: MYSQL_PASSWORD
  - source: 127.0.0.1



